#!/bin/bash
if [[ -z $(git status -s) ]]
then
  git push origin $BRANCH
  git fetch origin $RELEASE_BRANCH_NAME
  git rebase $RELEASE_BRANCH_NAME
  git checkout --ours .
  git rebase --continue
  COUNT=$(git rev-list --count HEAD ^$RELEASE_BRANCH_NAME)
  echo $COUNT
  git rebase -i HEAD~$COUNT  echo "tree is clean"
else
  echo "uncommited changes, please commit changes before running this"
  exit
fi

